name: Deploy Staging

on:
  push:
    branches:
      - 'release/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: echo "Deploy Staging ..."