# This is a basic workflow to help you get started with Actions

name: Integration Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify here the plugin installation environment. Can be development / staging / production. Empty field = staging'
        type: string
  workflow_run:
   workflows:
     - Deploy Staging
   types:
     - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  reinstall-latest-plugin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run script.sh
        run: | 
          chmod +x the_file_name
          ./script.sh
  run-integration-tests:
    needs: [reinstall-latest-plugin]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: 'gileli121/integration-tests-dummy'
          submodules: 'recursive'

      # Runs a single command using the runners shell
      - name: Run script.sh
        run: ./script.sh
        
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Report Tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: NUnit Tests
          path: TestResults/test-results.trx
          reporter: dotnet-trx
          fail-on-error: 'false'
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: TestResults/**
      

