# This is a basic workflow to help you get started with Actions

name: Integration Tests - Staging

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify here the plugin installation environment. Can be development / staging / production. Empty field = staging'
        type: string
  workflow_run:
   workflows:
     - Deploy Staging
   types:
     - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Print the environment input
      run: echo The environment is ${{ inputs.environment }}
  
  call-run-integration-tests:
    needs: [print-environment]
    uses: gileli121/integration-tests-dummy/.github/workflows/integration-tests.yml@master
    with:
      environment: Staging
